# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/testtest',
                'doc_host': 'https://fligt.github.io',
                'git_url': 'https://github.com/fligt/testtest',
                'lib_path': 'testtest'},
  'syms': {'testtest.core': {'testtest.core.foo': ('core.html#foo', 'testtest/core.py')}}}
